language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls

install:
  - pip install .
  - pip install pytest-cov

script:
  py.test --cov idoit --cov-report=term-missing -v tests/

after_script:
  coveralls --verbose
